setemeanalysis("Propagation sweep", 1);
setemeanalysis("parameter", "group span 2");
setemeanalysis("start", 96e-6);
setemeanalysis("stop", 97e-6);
setemeanalysis("number of points", 100);

emesweep;

S = getemesweep("S");

span = S.group_span_2*1e6;

s21 = 10*log10(abs(S.s21)^2);
s31 = 10*log10(abs(S.s31)^2);

plot(span, s21, "Comprimento do box", "Transmissao", "Transmissao x span", "linewidth = 3");
holdon;
plot(span, s31, "", "", "", "linewidth = 3");
holdoff;